version: '3'
services: 
  db:
    image: mysql:8.0.32
    environment: 
      MYSQL_DATABASE: my_movie_list
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - my_movie_list
  www:
    depends_on:
      - db
    image: php:8.2.4-apache
    volumes:
      - './:/var/www/html'
    ports:
      - 80:80
      - 443:443
    networks:
      - my_movie_list
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - my_movie_list
networks:
  my_movie_list:
    driver: bridge

      